using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Gunluk.Migrations
{
    public partial class First : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Kategoriler",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Ad = table.Column<string>(type: "nvarchar(100)", maxLength: 100, nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Kategoriler", x => x.Id);
                });

            migrationBuilder.CreateTable(
                name: "Gonderiler",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    Baslik = table.Column<string>(type: "nvarchar(400)", maxLength: 400, nullable: false),
                    Icerik = table.Column<string>(type: "nvarchar(max)", nullable: true),
                    Resim = table.Column<string>(type: "nvarchar(255)", maxLength: 255, nullable: true),
                    OlusturulmaZamani = table.Column<DateTime>(type: "datetime2", nullable: false),
                    DegistirilmeZamani = table.Column<DateTime>(type: "datetime2", nullable: false),
                    KategoriId = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Gonderiler", x => x.Id);
                    table.ForeignKey(
                        name: "FK_Gonderiler_Kategoriler_KategoriId",
                        column: x => x.KategoriId,
                        principalTable: "Kategoriler",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.InsertData(
                table: "Kategoriler",
                columns: new[] { "Id", "Ad" },
                values: new object[,]
                {
                    { 1, "Is Dunyasi" },
                    { 2, "Gezilerim" },
                    { 3, "Mutfagim" },
                    { 4, "Karisik" }
                });

            migrationBuilder.InsertData(
                table: "Gonderiler",
                columns: new[] { "Id", "Baslik", "DegistirilmeZamani", "Icerik", "KategoriId", "OlusturulmaZamani", "Resim" },
                values: new object[,]
                {
                    { 1, "Ornek Yazi 1", new DateTime(2023, 1, 4, 15, 13, 17, 447, DateTimeKind.Local).AddTicks(9991), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 4, 15, 13, 17, 447, DateTimeKind.Local).AddTicks(9983), null },
                    { 2, "Ornek Yazi 2", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(17), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(16), null },
                    { 3, "Ornek Yazi 3", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(18), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(18), null },
                    { 4, "Ornek Yazi 4", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(19), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(19), null },
                    { 5, "Ornek Yazi 5", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(20), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(20), null },
                    { 6, "Ornek Yazi 6", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(63), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(62), null },
                    { 7, "Ornek Yazi 7", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(64), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(64), null },
                    { 8, "Ornek Yazi 8", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(66), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(65), null },
                    { 9, "Ornek Yazi 9", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(67), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(67), null },
                    { 10, "Ornek Yazi 10", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(68), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(68), null },
                    { 11, "Ornek Yazi 11", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(70), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(69), null },
                    { 12, "Ornek Yazi 12", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(71), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 1, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(71), null },
                    { 13, "Ornek Yazi 13", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(72), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(72), null },
                    { 14, "Ornek Yazi 14", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(74), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(73), null },
                    { 15, "Ornek Yazi 15", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(75), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(74), null },
                    { 16, "Ornek Yazi 16", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(76), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(76), null },
                    { 17, "Ornek Yazi 17", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(77), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(77), null },
                    { 18, "Ornek Yazi 18", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(78), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(78), null },
                    { 19, "Ornek Yazi 19", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(80), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(79), null },
                    { 20, "Ornek Yazi 20", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(81), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(81), null },
                    { 21, "Ornek Yazi 21", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(82), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(82), null },
                    { 22, "Ornek Yazi 22", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(83), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(83), null },
                    { 23, "Ornek Yazi 23", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(84), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(84), null },
                    { 24, "Ornek Yazi 24", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(86), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 2, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(85), null },
                    { 25, "Ornek Yazi 25", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(87), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(87), null },
                    { 26, "Ornek Yazi 26", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(88), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(88), null },
                    { 27, "Ornek Yazi 27", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(90), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(89), null },
                    { 28, "Ornek Yazi 28", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(91), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(91), null },
                    { 29, "Ornek Yazi 29", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(92), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(92), null },
                    { 30, "Ornek Yazi 30", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(93), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(93), null },
                    { 31, "Ornek Yazi 31", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(94), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(94), null },
                    { 32, "Ornek Yazi 32", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(96), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(95), null },
                    { 33, "Ornek Yazi 33", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(97), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(97), null },
                    { 34, "Ornek Yazi 34", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(98), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(98), null },
                    { 35, "Ornek Yazi 35", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(99), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(99), null },
                    { 36, "Ornek Yazi 36", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(101), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 3, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(100), null },
                    { 37, "Ornek Yazi 37", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(102), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(101), null },
                    { 38, "Ornek Yazi 38", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(103), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(103), null },
                    { 39, "Ornek Yazi 39", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(104), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(104), null },
                    { 40, "Ornek Yazi 40", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(105), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(105), null },
                    { 41, "Ornek Yazi 41", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(107), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(106), null },
                    { 42, "Ornek Yazi 42", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(108), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(108), null }
                });

            migrationBuilder.InsertData(
                table: "Gonderiler",
                columns: new[] { "Id", "Baslik", "DegistirilmeZamani", "Icerik", "KategoriId", "OlusturulmaZamani", "Resim" },
                values: new object[,]
                {
                    { 43, "Ornek Yazi 43", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(109), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(109), null },
                    { 44, "Ornek Yazi 44", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(110), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(110), null },
                    { 45, "Ornek Yazi 45", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(112), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(111), null },
                    { 46, "Ornek Yazi 46", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(113), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(113), null },
                    { 47, "Ornek Yazi 47", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(114), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(114), null },
                    { 48, "Ornek Yazi 48", new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(115), "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>", 4, new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(115), null }
                });

            migrationBuilder.CreateIndex(
                name: "IX_Gonderiler_KategoriId",
                table: "Gonderiler",
                column: "KategoriId");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Gonderiler");

            migrationBuilder.DropTable(
                name: "Kategoriler");
        }
    }
}
