// <auto-generated />
using System;
using Gunluk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Gunluk.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20230104121317_First")]
    partial class First
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Gunluk.Data.Gonderi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Baslik")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<DateTime>("DegistirilmeZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icerik")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OlusturulmaZamani")
                        .HasColumnType("datetime2");

                    b.Property<string>("Resim")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Gonderiler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Baslik = "Ornek Yazi 1",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 447, DateTimeKind.Local).AddTicks(9991),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 447, DateTimeKind.Local).AddTicks(9983)
                        },
                        new
                        {
                            Id = 2,
                            Baslik = "Ornek Yazi 2",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(17),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(16)
                        },
                        new
                        {
                            Id = 3,
                            Baslik = "Ornek Yazi 3",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(18),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(18)
                        },
                        new
                        {
                            Id = 4,
                            Baslik = "Ornek Yazi 4",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(19),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(19)
                        },
                        new
                        {
                            Id = 5,
                            Baslik = "Ornek Yazi 5",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(20),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(20)
                        },
                        new
                        {
                            Id = 6,
                            Baslik = "Ornek Yazi 6",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(63),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(62)
                        },
                        new
                        {
                            Id = 7,
                            Baslik = "Ornek Yazi 7",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(64),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(64)
                        },
                        new
                        {
                            Id = 8,
                            Baslik = "Ornek Yazi 8",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(66),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(65)
                        },
                        new
                        {
                            Id = 9,
                            Baslik = "Ornek Yazi 9",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(67),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(67)
                        },
                        new
                        {
                            Id = 10,
                            Baslik = "Ornek Yazi 10",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(68),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(68)
                        },
                        new
                        {
                            Id = 11,
                            Baslik = "Ornek Yazi 11",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(70),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(69)
                        },
                        new
                        {
                            Id = 12,
                            Baslik = "Ornek Yazi 12",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(71),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 1,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(71)
                        },
                        new
                        {
                            Id = 13,
                            Baslik = "Ornek Yazi 13",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(72),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(72)
                        },
                        new
                        {
                            Id = 14,
                            Baslik = "Ornek Yazi 14",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(74),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(73)
                        },
                        new
                        {
                            Id = 15,
                            Baslik = "Ornek Yazi 15",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(75),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(74)
                        },
                        new
                        {
                            Id = 16,
                            Baslik = "Ornek Yazi 16",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(76),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(76)
                        },
                        new
                        {
                            Id = 17,
                            Baslik = "Ornek Yazi 17",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(77),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(77)
                        },
                        new
                        {
                            Id = 18,
                            Baslik = "Ornek Yazi 18",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(78),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(78)
                        },
                        new
                        {
                            Id = 19,
                            Baslik = "Ornek Yazi 19",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(80),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(79)
                        },
                        new
                        {
                            Id = 20,
                            Baslik = "Ornek Yazi 20",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(81),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(81)
                        },
                        new
                        {
                            Id = 21,
                            Baslik = "Ornek Yazi 21",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(82),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(82)
                        },
                        new
                        {
                            Id = 22,
                            Baslik = "Ornek Yazi 22",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(83),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(83)
                        },
                        new
                        {
                            Id = 23,
                            Baslik = "Ornek Yazi 23",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(84),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(84)
                        },
                        new
                        {
                            Id = 24,
                            Baslik = "Ornek Yazi 24",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(86),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 2,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(85)
                        },
                        new
                        {
                            Id = 25,
                            Baslik = "Ornek Yazi 25",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(87),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(87)
                        },
                        new
                        {
                            Id = 26,
                            Baslik = "Ornek Yazi 26",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(88),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(88)
                        },
                        new
                        {
                            Id = 27,
                            Baslik = "Ornek Yazi 27",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(90),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(89)
                        },
                        new
                        {
                            Id = 28,
                            Baslik = "Ornek Yazi 28",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(91),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(91)
                        },
                        new
                        {
                            Id = 29,
                            Baslik = "Ornek Yazi 29",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(92),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(92)
                        },
                        new
                        {
                            Id = 30,
                            Baslik = "Ornek Yazi 30",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(93),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(93)
                        },
                        new
                        {
                            Id = 31,
                            Baslik = "Ornek Yazi 31",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(94),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(94)
                        },
                        new
                        {
                            Id = 32,
                            Baslik = "Ornek Yazi 32",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(96),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(95)
                        },
                        new
                        {
                            Id = 33,
                            Baslik = "Ornek Yazi 33",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(97),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(97)
                        },
                        new
                        {
                            Id = 34,
                            Baslik = "Ornek Yazi 34",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(98),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(98)
                        },
                        new
                        {
                            Id = 35,
                            Baslik = "Ornek Yazi 35",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(99),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(99)
                        },
                        new
                        {
                            Id = 36,
                            Baslik = "Ornek Yazi 36",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(101),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 3,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(100)
                        },
                        new
                        {
                            Id = 37,
                            Baslik = "Ornek Yazi 37",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(102),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(101)
                        },
                        new
                        {
                            Id = 38,
                            Baslik = "Ornek Yazi 38",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(103),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(103)
                        },
                        new
                        {
                            Id = 39,
                            Baslik = "Ornek Yazi 39",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(104),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(104)
                        },
                        new
                        {
                            Id = 40,
                            Baslik = "Ornek Yazi 40",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(105),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(105)
                        },
                        new
                        {
                            Id = 41,
                            Baslik = "Ornek Yazi 41",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(107),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(106)
                        },
                        new
                        {
                            Id = 42,
                            Baslik = "Ornek Yazi 42",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(108),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(108)
                        },
                        new
                        {
                            Id = 43,
                            Baslik = "Ornek Yazi 43",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(109),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(109)
                        },
                        new
                        {
                            Id = 44,
                            Baslik = "Ornek Yazi 44",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(110),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(110)
                        },
                        new
                        {
                            Id = 45,
                            Baslik = "Ornek Yazi 45",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(112),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(111)
                        },
                        new
                        {
                            Id = 46,
                            Baslik = "Ornek Yazi 46",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(113),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(113)
                        },
                        new
                        {
                            Id = 47,
                            Baslik = "Ornek Yazi 47",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(114),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(114)
                        },
                        new
                        {
                            Id = 48,
                            Baslik = "Ornek Yazi 48",
                            DegistirilmeZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(115),
                            Icerik = "\r\n<p>Tincidunt integer eu augue augue nunc elit dolor, luctus placerat scelerisque euismod, iaculiseulacusnunmelitvehiculaulaoreeacaliquam sit amet justo nunc tempor, metus vel.</p>\r\n<p>Placerat suscipit, orci nisl iaculis eros, a tincidunt nisi odio eget lorem nulla condimentum tempor mattis  ut   vitae      feugiat      augue   cras  ut metus a risus iaculis scelerisque eu ac ante.</p>",
                            KategoriId = 4,
                            OlusturulmaZamani = new DateTime(2023, 1, 4, 15, 13, 17, 448, DateTimeKind.Local).AddTicks(115)
                        });
                });

            modelBuilder.Entity("Gunluk.Data.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Is Dunyasi"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Gezilerim"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Mutfagim"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Karisik"
                        });
                });

            modelBuilder.Entity("Gunluk.Data.Gonderi", b =>
                {
                    b.HasOne("Gunluk.Data.Kategori", "Kategori")
                        .WithMany("Gonderiler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("Gunluk.Data.Kategori", b =>
                {
                    b.Navigation("Gonderiler");
                });
#pragma warning restore 612, 618
        }
    }
}
